"""card

Revision ID: 24b6ca9091d0
Revises: a5a52cba7278
Create Date: 2025-03-16 00:28:27.739402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b6ca9091d0'
down_revision = 'a5a52cba7278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_owner', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_name')
        batch_op.drop_column('sort_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_code', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('bank_name')
        batch_op.drop_column('card_number')
        batch_op.drop_column('card_owner')

    # ### end Alembic commands ###
