"""consults

Revision ID: 366cf6339cac
Revises: 3be4ede3df08
Create Date: 2025-03-19 16:48:33.348199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366cf6339cac'
down_revision = '3be4ede3df08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('l_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('l_name')
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###
