"""Edit Cart

Revision ID: 3be4ede3df08
Revises: 85b078833cf5
Create Date: 2025-03-19 01:11:57.844127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be4ede3df08'
down_revision = '85b078833cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('post_code')
        batch_op.drop_column('reciver_l_name')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('name')
        batch_op.drop_column('plaque')
        batch_op.drop_column('phone')
        batch_op.drop_column('reciver_f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reciver_f_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('plaque', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('reciver_l_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('post_code', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
