"""User

Revision ID: 85b078833cf5
Revises: 24b6ca9091d0
Create Date: 2025-03-17 15:55:46.892374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b078833cf5'
down_revision = '24b6ca9091d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('l_name')
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('l_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
